import type { GraphEdge, GraphNode, NodePosition } from '@/types/graph';
import type { Memory } from '@/types/memory';

const T0 = 1_790_000_000_000;

export const GREENLAND_NODES: readonly GraphNode[] = [
  {
    id: 'n1',
    role: 'user',
    type: 'message',
    text: 'Production dashboard freezes after ~20 minutes. The browser tab pegs a CPU core and the WebSocket reconnect counter is spiking into the thousands per second.',
    label: 'Dashboard freezes in prod',
    parentId: null,
    timestamp: T0,
    metadata: { tokens: 41 },
  },
  {
    id: 'n2',
    role: 'ai',
    type: 'message',
    text: 'That pattern is almost always a reconnect storm with no backoff. Every failed socket immediately retries, and if a re-render is also re-subscribing, the listeners pile up.',
    label: 'Reconnect storm, no backoff',
    parentId: 'n1',
    timestamp: T0 + 1,
    metadata: {
      model: 'anthropic/claude-sonnet-4',
      tokens: 88,
      thinking: [
        { label: 'Symptom', content: 'CPU-bound freeze and thousands of reconnects indicate a tight retry loop.' },
        { label: 'Hypotheses', content: 'No exponential backoff, listener leak on re-render, or server-side connection churn.' },
      ],
    },
  },
  {
    id: 'n3',
    role: 'user',
    type: 'message',
    text: 'Here is the hook. useSocket subscribes in a useEffect and the onMessage handler is defined inline in the component.',
    label: 'useSocket hook',
    parentId: 'n2',
    timestamp: T0 + 2,
    metadata: { tokens: 34 },
  },
  {
    id: 'n4',
    role: 'ai',
    type: 'message',
    text: 'Found it. The useEffect lists onMessage in its deps, but onMessage is re-created every render, so the effect tears down and re-subscribes on every render.',
    label: 'Found listener leak',
    parentId: 'n3',
    timestamp: T0 + 3,
    metadata: {
      model: 'anthropic/claude-sonnet-4',
      tokens: 102,
      thinking: [
        { label: 'Root cause', content: 'Unstable onMessage identity causes the effect to re-subscribe every render.' },
        { label: 'Fix path', content: 'Memoize handlers, clean up on unmount, then add transport-level backoff.' },
      ],
    },
  },
  {
    id: 'b1',
    role: 'user',
    type: 'message',
    text: 'Could the load balancer be dropping idle connections and forcing the reconnects?',
    label: 'Could LB be dropping idle?',
    parentId: 'n4',
    timestamp: T0 + 4,
    metadata: { tokens: 28 },
  },
  {
    id: 'b2',
    role: 'ai',
    type: 'message',
    text: 'Possible. Check the ELB idle-timeout. If it is below the heartbeat interval, idle sockets get culled.',
    label: 'Check ELB idle timeout',
    parentId: 'b1',
    timestamp: T0 + 5,
    metadata: { model: 'anthropic/claude-sonnet-4', tokens: 36 },
  },
  {
    id: 'b3',
    role: 'user',
    type: 'message',
    text: 'Idle timeout is 3600s and heartbeats are every 30s. Not the load balancer.',
    label: 'Nope - 3600s',
    parentId: 'b2',
    timestamp: T0 + 6,
    metadata: { tokens: 22 },
  },
  {
    id: 'sum',
    role: 'ai',
    type: 'summary',
    text: 'Branch summary: load-balancer idle-timeout was investigated and ruled out. Root cause is client-side.',
    label: 'LB hypothesis ruled out',
    parentId: 'b1',
    timestamp: T0 + 7,
    metadata: { model: 'google/gemini-2.0-flash', tokens: 31 },
  },
  {
    id: 'n5',
    role: 'user',
    type: 'message',
    text: 'Let us fix the leak. How do I stop the effect from re-subscribing every render?',
    label: 'Fix listener leak',
    parentId: 'n4',
    timestamp: T0 + 8,
    metadata: { tokens: 24 },
  },
  {
    id: 'n6',
    role: 'ai',
    type: 'message',
    text: 'Wrap onMessage in useCallback with a stable dependency array, and return a cleanup from the effect that removes the listener.',
    label: 'useCallback + cleanup',
    parentId: 'n5',
    timestamp: T0 + 9,
    metadata: {
      model: 'anthropic/claude-sonnet-4',
      tokens: 79,
      thinking: [
        { label: 'Mechanism', content: 'Stable handler identity keeps effect dependencies unchanged.' },
        { label: 'Cleanup', content: 'Remove the exact listener reference on unmount.' },
      ],
    },
  },
  {
    id: 'r1',
    role: 'ai',
    type: 'message',
    text: 'Alternative: lift the socket into a React context provider at the app root so it is created exactly once.',
    label: 'Alt: socket context',
    parentId: 'n5',
    timestamp: T0 + 10,
    metadata: { model: 'openai/gpt-4o', tokens: 61 },
  },
  {
    id: 'n7',
    role: 'user',
    type: 'message',
    text: 'Applied the useCallback + cleanup. Leak is gone locally, but under production load the reconnect counter still climbs when the backend redeploys.',
    label: 'Applied - still spiking',
    parentId: 'n6',
    timestamp: T0 + 11,
    metadata: { tokens: 33 },
  },
  {
    id: 'n8',
    role: 'ai',
    type: 'message',
    text: 'That is the other half. On redeploy every client drops at once and retries instantly, hammering the backend as it comes up.',
    label: 'Needs exponential backoff',
    parentId: 'n7',
    timestamp: T0 + 12,
    metadata: {
      model: 'anthropic/claude-sonnet-4',
      tokens: 71,
      thinking: [
        { label: 'Second cause', content: 'Synchronized reconnects on redeploy create a thundering herd.' },
        { label: 'Remedy', content: 'Exponential backoff spreads retries across time.' },
      ],
    },
  },
  {
    id: 'n9',
    role: 'user',
    type: 'message',
    text: 'Added a basic exponential backoff: delay doubles each attempt starting at 250ms.',
    label: 'Backoff added',
    parentId: 'n8',
    timestamp: T0 + 13,
    metadata: { tokens: 21 },
  },
  {
    id: 'n10',
    role: 'ai',
    type: 'message',
    text: 'Last piece: add jitter and a ceiling. Pure exponential backoff still synchronizes because every client doubles in lockstep. Multiply the delay by a random factor and cap it around ten seconds.',
    label: 'Add jitter + a cap',
    parentId: 'n9',
    timestamp: T0 + 14,
    metadata: {
      model: 'anthropic/claude-sonnet-4',
      tokens: 96,
      thinking: [
        { label: 'Why jitter', content: 'Deterministic backoff keeps clients phase-locked; randomization breaks the sync.' },
        { label: 'Why a cap', content: 'Unbounded growth strands clients offline after an outage; ten seconds keeps recovery snappy.' },
        { label: 'Result', content: 'Reconnects per second drop from roughly 3000 to fewer than 20 across a redeploy.' },
      ],
    },
  },
  {
    id: 'clip',
    role: 'ai',
    type: 'clip',
    text: 'Reusable pattern: jittered exponential backoff with a ten second cap for WebSocket reconnects. Memoize handlers, cleanup on unmount, randomize retry delay.',
    label: 'Reconnect backoff pattern',
    parentId: 'n10',
    timestamp: T0 + 15,
    metadata: { model: 'anthropic/claude-sonnet-4', tokens: 44 },
  },
  {
    id: 'nS',
    role: 'ai',
    type: 'message',
    text: '',
    label: 'Verifying under load',
    parentId: 'n10',
    timestamp: T0 + 16,
    metadata: { model: 'anthropic/claude-sonnet-4', tokens: 0 },
  },
];

export const GREENLAND_EDGES: readonly GraphEdge[] = [
  { id: 'e1', from: 'n1', to: 'n2', type: 'reply', weight: 1 },
  { id: 'e2', from: 'n2', to: 'n3', type: 'reply', weight: 1 },
  { id: 'e3', from: 'n3', to: 'n4', type: 'reply', weight: 1 },
  { id: 'e4', from: 'n4', to: 'b1', type: 'branch', weight: 0.55 },
  { id: 'e5', from: 'b1', to: 'b2', type: 'reply', weight: 0.55 },
  { id: 'e6', from: 'b2', to: 'b3', type: 'reply', weight: 0.55 },
  { id: 'e7', from: 'b1', to: 'sum', type: 'summarizes', weight: 0.45 },
  { id: 'e8', from: 'n4', to: 'n5', type: 'branch', weight: 1 },
  { id: 'e9', from: 'n5', to: 'n6', type: 'reply', weight: 1 },
  { id: 'e10', from: 'n5', to: 'r1', type: 'regeneration', weight: 0.48 },
  { id: 'e11', from: 'n6', to: 'n7', type: 'reply', weight: 1 },
  { id: 'e12', from: 'n7', to: 'n8', type: 'reply', weight: 1 },
  { id: 'e13', from: 'n8', to: 'n9', type: 'reply', weight: 1 },
  { id: 'e14', from: 'n9', to: 'n10', type: 'reply', weight: 1 },
  { id: 'e15', from: 'n10', to: 'clip', type: 'clips_to', weight: 0.62 },
  { id: 'e16', from: 'n10', to: 'nS', type: 'reply', weight: 1 },
];

export const GREENLAND_POSITIONS: Record<string, NodePosition> = {
  n1: { x: 60, y: 40 },
  n2: { x: 20, y: 158 },
  n3: { x: 78, y: 276 },
  n4: { x: 24, y: 396 },
  b1: { x: 300, y: 360 },
  b2: { x: 432, y: 432 },
  b3: { x: 366, y: 552 },
  sum: { x: 486, y: 470 },
  n5: { x: -132, y: 486 },
  n6: { x: -176, y: 606 },
  r1: { x: -372, y: 612 },
  n7: { x: -120, y: 726 },
  n8: { x: -168, y: 846 },
  n9: { x: -120, y: 966 },
  n10: { x: -168, y: 1086 },
  clip: { x: 60, y: 1040 },
  nS: { x: -150, y: 1212 },
};

export const GREENLAND_ACTIVE_NODE_ID = 'n10';

export const GREENLAND_MEMORIES: readonly Memory[] = [
  {
    id: 'memory-backoff',
    name: 'Reconnect backoff pattern',
    content: 'Jittered exponential backoff with a ten second cap prevents synchronized reconnect storms after backend redeploys.',
    context: 'Saved from the branch that resolves WebSocket reconnect storms.',
    tags: ['reconnect', 'stability'],
    sourceNodeId: 'clip',
    sourcePathNodeIds: ['n8', 'n9', 'n10', 'clip'],
    createdAt: T0 + 20,
    type: 'subgraph',
    graphSnapshot: {
      nodes: GREENLAND_NODES.filter(node => ['n8', 'n9', 'n10', 'clip'].includes(node.id)),
      edges: GREENLAND_EDGES.filter(edge => ['n8', 'n9', 'n10', 'clip'].includes(edge.from) && ['n8', 'n9', 'n10', 'clip'].includes(edge.to)),
    },
  },
  {
    id: 'memory-cleanup',
    name: 'Stable listener cleanup',
    content: 'Wrap WebSocket message handlers in useCallback and remove the exact listener reference during effect cleanup.',
    context: 'Saved from the listener leak fix path.',
    tags: ['react', 'sockets'],
    sourceNodeId: 'n6',
    sourcePathNodeIds: ['n1', 'n2', 'n3', 'n4', 'n5', 'n6'],
    createdAt: T0 + 21,
    type: 'path',
  },
  {
    id: 'memory-ruled-out',
    name: 'Load balancer ruled out',
    content: 'ELB idle timeout was not the cause because the timeout was far above the heartbeat interval.',
    context: 'Saved from the alternate branch investigating infrastructure causes.',
    tags: ['infra'],
    sourceNodeId: 'sum',
    sourcePathNodeIds: ['n1', 'n2', 'n3', 'n4', 'b1', 'sum'],
    createdAt: T0 + 22,
    type: 'node',
  },
];
